theme: jekyll-theme-slate
title: Vishal Singh
description: Blockchain-Cryptography Security Researcher
url: "https://this-vishalsingh.github.io"
twitter_username: thisvishalsingh
github_username: this-vishalsingh
